/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts'
export type { contracts }
export type { MyOApp } from './contracts/MyOApp'
export type { MyToken } from './contracts/MyToken'
